name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'brexhq/kotlin-language-server-bazel-support'
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ contains(matrix.os, 'windows') }}
      - name: Get tag name
        id: tag
        run: |
          tag=$(basename "${{ github.ref }}")
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Build distribution
        run: ./gradlew :server:distZip :adapter:distZip
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          gh release create "$tag" --title "Version $tag"
      - name: Upload assets
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          cp server/build/distributions/server.zip server/build/distributions/kotlin-language-server.zip
          cp adapter/build/distributions/adapter.zip adapter/build/distributions/kotlin-debug-adapter.zip
          gh release upload "$tag" server/build/distributions/*
          gh release upload "$tag" adapter/build/distributions/*
